name: flutter_demo_new
description: some demo

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  fluro: ^1.3.7
  path_provider: ^1.4.5
  english_words: ^3.1.4
  intl: 0.15.7
  intl_translation: 0.17.2

  numberpicker: ^0.1.7
  # camera: "^0.2.4"
  video_player: 0.7.2
  image_picker: ^0.6.1+4
  signature_pad_flutter: ^1.2.0
  flutter_webview_plugin: ^0.3.5
  webview_flutter: ^0.3.15+1
  rxdart: ^0.22.1+1
  bloc: ^0.15.0
  event_bus: ^1.1.0
  fluttertoast: ^3.1.3

  # flutter_user_agent: ^1.0.1
  package_info: ^0.4.0+6
  shared_preferences: ^0.5.3+1
  # image_carousel: ^0.4.1
  # multi_image_picker: ^4.5.5

  pull_to_refresh: ^1.5.6
  flutter_progress_hud: ^1.0.2
  exif: ^1.0.1
  flutter_image_compress: ^0.6.1
  cached_network_image: ^2.0.0-rc.1
  amap_location: ^0.2.0
  url_launcher: ^5.2.7
  maps_launcher: ^1.0.1
  flutter_2d_amap:
    git:
      url: https://github.com/simplezhli/flutter_2d_amap.git

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - static/images/index_colours.png
    - static/images/index_gray.png
    - static/images/learn_colours.png
    - static/images/learn_gray.png
    - static/images/enjoyment_colours.png
    - static/images/enjoyment_gray.png
    - static/images/user_colours.png
    - static/images/user_gray.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
